<?php
/**
 * Web 安装程序
 * 访问 /install/install.php
 */

session_start();
$base = dirname(__DIR__);

// 安全读取 .env（不依赖 putenv/getenv（可能被 disable_functions 禁用）
if (!function_exists('mail_sys_env_read')) {
    function mail_sys_env_read(string $key, $default = '') {
        if (isset($_ENV[$key]) && $_ENV[$key] !== '') return $_ENV[$key];
        $envFile = dirname(__DIR__) . '/.env';
        if (!file_exists($envFile)) return $default;
        $lines = @file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        if (!is_array($lines)) return $default;
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '' || strpos($line, '#') === 0) continue;
            if (strpos($line, '=') === false) continue;
            [$k, $v] = explode('=', $line, 2);
            $k = trim($k); $v = trim($v);
            if ((str_starts_with($v, '"') && str_ends_with($v, '"')) ||
                (str_starts_with($v, "'") && str_ends_with($v, "'"))) {
                $v = substr($v, 1, -1);
            }
            $_ENV[$k] = $v;
        }
        return $_ENV[$key] ?? $default;
    }
}

$lockFile = $base . '/storage/installed.lock';
$installed = file_exists($lockFile);

$step = (int) ($_GET['step'] ?? 1);

if ($installed && $step !== 99) {
    echo '<h1>系统已安装</h1><p>如需重新安装，请删除 storage/installed.lock 文件。</p>';
    exit;
}

function checkEnvironment() {
    $checks = [];
    $checks[] = ['PHP >= 7.4',     version_compare(PHP_VERSION, '7.4.0', '>='), PHP_VERSION];
    $checks[] = ['PDO MySQL',      extension_loaded('pdo_mysql'), '必需'];
    $checks[] = ['OpenSSL',        extension_loaded('openssl'), 'SSL 端口需要'];
    $checks[] = ['mbstring',       extension_loaded('mbstring'), 'MIME 解析'];
    $checks[] = ['iconv',          extension_loaded('iconv'), '编码转换'];
    $checks[] = ['Sockets (可选)', extension_loaded('sockets'), '高性能 socket'];
    $checks[] = ['pcntl (可选)',   extension_loaded('pcntl'), '进程管理'];
    $checks[] = ['storage 目录可写', is_writable($base . '/storage'), $base . '/storage'];
    $checks[] = ['data 目录可写',    is_writable($base . '/data') || @mkdir($base . '/data', 0755, true), $base . '/data'];
    $checks[] = ['config 目录可写',  is_writable($base . '/config'), $base . '/config'];
    return $checks;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    // 测试数据库连接
    $host = $_POST['db_host'] ?? '127.0.0.1';
    $port = (int) ($_POST['db_port'] ?? 3306);
    $name = $_POST['db_name'] ?? 'mail_system';
    $user = $_POST['db_user'] ?? 'root';
    $pass = $_POST['db_pass'] ?? '';
    try {
        $pdo = new PDO("mysql:host=$host;port=$port;charset=utf8mb4", $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        // 创建数据库
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$name` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        // 导入 schema
        $pdo->exec("USE `$name`");
        $sql = file_get_contents($base . '/database/schema.sql');
        // 移除 DEFINER/FOREIGN_KEY 等
        $sql = preg_replace('/SET FOREIGN_KEY_CHECKS = [01];/i', '', $sql);
        $pdo->exec($sql);

        // 写入 .env
        $appKey = bin2hex(random_bytes(16));
        $adminPath = trim($_POST['admin_path'] ?? 'admin');
        $adminPort = trim($_POST['admin_port'] ?? '8080');
        $smtpBanner = 'MailSystem ESMTP';
        $envContent = "# MailSystem Config - Generated by Installer\n";
        $envContent .= "APP_NAME=MailSystem\n";
        $envContent .= "APP_ENV=production\n";
        $envContent .= "APP_DEBUG=false\n";
        $envContent .= "APP_URL=" . ($_POST['app_url'] ?? 'http://localhost') . "\n";
        $envContent .= "APP_TIMEZONE=" . ($_POST['timezone'] ?? 'Asia/Shanghai') . "\n";
        $envContent .= "APP_KEY=$appKey\n\n";
        $envContent .= "DB_HOST=$host\n";
        $envContent .= "DB_PORT=$port\n";
        $envContent .= "DB_DATABASE=$name\n";
        $envContent .= "DB_USERNAME=$user\n";
        $envContent .= "DB_PASSWORD=$pass\n";
        $envContent .= "DB_CHARSET=utf8mb4\n\n";
        $envContent .= "ADMIN_PATH=$adminPath\n";
        $envContent .= "ADMIN_PORT=$adminPort\n";
        $envContent .= "WEB_PORT=80\n\n";
        $envContent .= "MAIL_HOSTNAME=" . ($_POST['mail_hostname'] ?? 'mail.local') . "\n";
        $envContent .= "LOG_PATH=$base/logs\n";

        file_put_contents($base . '/.env', $envContent);

        // 创建管理员
        $adminUser = trim($_POST['admin_user'] ?? 'admin');
        $adminPass = $_POST['admin_pass'] ?? '';
        $adminEmail= trim($_POST['admin_email'] ?? 'admin@localhost');
        $pdo->prepare("UPDATE ms_users SET username = ?, password = ?, email = ?, display_name = '系统管理员' WHERE username = 'admin'")
            ->execute([$adminUser, password_hash($adminPass, PASSWORD_DEFAULT), $adminEmail]);

        // 更新设置
        $pdo->prepare("UPDATE ms_settings SET `value` = ? WHERE key_name = 'admin_path'")->execute([$adminPath]);
        $pdo->prepare("UPDATE ms_settings SET `value` = ? WHERE key_name = 'admin_port'")->execute([$adminPort]);
        $pdo->prepare("UPDATE ms_settings SET `value` = ? WHERE key_name = 'mail_hostname'")->execute([$_POST['mail_hostname'] ?? 'mail.local']);
        $pdo->prepare("UPDATE ms_settings SET `value` = ? WHERE key_name = 'site_name'")->execute(['MailSystem']);

        @mkdir($base . '/data/mailboxes', 0755, true);
        @mkdir($base . '/storage/cache', 0755, true);
        @mkdir($base . '/storage/sessions', 0755, true);
        @mkdir($base . '/logs', 0755, true);

        // 锁定
        file_put_contents($lockFile, json_encode([
            'installed_at' => date('Y-m-d H:i:s'),
            'version' => '1.0.0',
        ]));

        $_SESSION['install_success'] = true;
        header('Location: /install/install.php?step=3');
        exit;
    } catch (Throwable $e) {
        $err = $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>MailSystem 安装向导</title>
<style>
body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; background: #f5f7fa; margin: 0; padding: 30px; }
.container { max-width: 720px; margin: 30px auto; background: #fff; border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); overflow: hidden; }
.header { background: linear-gradient(135deg, #667eea, #764ba2); color: #fff; padding: 30px; }
.header h1 { margin: 0; font-size: 26px; }
.header p  { margin: 8px 0 0; opacity: 0.9; }
.steps { display: flex; padding: 16px 30px; background: #fafbfc; border-bottom: 1px solid #e1e4e8; }
.steps .item { flex: 1; text-align: center; color: #999; padding: 8px; font-size: 14px; }
.steps .item.active { color: #667eea; font-weight: 600; }
.steps .item.done   { color: #28a745; }
.content { padding: 30px; }
.form-group { margin-bottom: 16px; }
.form-group label { display: block; font-size: 14px; color: #555; margin-bottom: 6px; }
.form-group input { width: 100%; padding: 9px 12px; border: 1px solid #d0d7de; border-radius: 5px; font-size: 14px; box-sizing: border-box; }
.form-group input:focus { outline: none; border-color: #667eea; }
.btn { padding: 10px 22px; border: none; border-radius: 5px; background: #667eea; color: #fff; font-size: 14px; cursor: pointer; }
.btn:hover { background: #556cd6; }
.btn-secondary { background: #6c757d; }
table { width: 100%; border-collapse: collapse; margin-top: 12px; }
table td, table th { padding: 8px 12px; border-bottom: 1px solid #e1e4e8; font-size: 14px; }
.check-ok    { color: #28a745; font-weight: bold; }
.check-fail  { color: #dc3545; font-weight: bold; }
.error { background: #f8d7da; color: #721c24; padding: 10px 14px; border-radius: 5px; margin-bottom: 16px; }
.success-box { background: #d4edda; color: #155724; padding: 20px; border-radius: 5px; }
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>📧 MailSystem 邮件系统</h1>
        <p>轻量级自托管邮件服务器 + Web 后台管理</p>
    </div>
    <div class="steps">
        <div class="item <?= $step >= 1 ? 'active' : '' ?><?= $step > 1 ? ' done' : '' ?>">1. 环境检测</div>
        <div class="item <?= $step >= 2 ? 'active' : '' ?><?= $step > 2 ? ' done' : '' ?>">2. 数据库配置</div>
        <div class="item <?= $step >= 3 ? 'active' : '' ?>">3. 安装完成</div>
    </div>
    <div class="content">
        <?php if ($step === 1): ?>
            <h2>第一步：环境检测</h2>
            <p>请确认以下检查项全部通过：</p>
            <table>
                <tr><th>检查项</th><th>状态</th><th>当前值</th></tr>
                <?php foreach (checkEnvironment() as $c):
                    $ok = $c[1];
                ?>
                <tr>
                    <td><?= htmlspecialchars($c[0]) ?></td>
                    <td class="<?= $ok ? 'check-ok' : 'check-fail' ?>"><?= $ok ? '✓ 通过' : '✗ 失败' ?></td>
                    <td><?= htmlspecialchars((string) $c[2]) ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
            <p style="margin-top:24px;">
                <a class="btn" href="?step=2">下一步</a>
            </p>
        <?php elseif ($step === 2): ?>
            <h2>第二步：数据库与管理配置</h2>
            <?php if (!empty($err)): ?>
                <div class="error">错误: <?= htmlspecialchars($err) ?></div>
            <?php endif; ?>
            <form method="post" action="?step=2">
                <h3>数据库 (MySQL)</h3>
                <div class="form-group">
                    <label>数据库主机</label>
                    <input type="text" name="db_host" value="127.0.0.1" required>
                </div>
                <div class="form-group">
                    <label>数据库端口</label>
                    <input type="number" name="db_port" value="3306" required>
                </div>
                <div class="form-group">
                    <label>数据库名 (不存在将自动创建)</label>
                    <input type="text" name="db_name" value="mail_system" required>
                </div>
                <div class="form-group">
                    <label>数据库用户</label>
                    <input type="text" name="db_user" value="root" required>
                </div>
                <div class="form-group">
                    <label>数据库密码</label>
                    <input type="password" name="db_pass" value="">
                </div>
                <h3>管理后台</h3>
                <div class="form-group">
                    <label>后台路径 (修改后 URL 变为 /你的路径/)</label>
                    <input type="text" name="admin_path" value="admin" required pattern="[a-zA-Z0-9_-]+">
                </div>
                <div class="form-group">
                    <label>后台端口 (提示用，nginx/apache 实际绑定)</label>
                    <input type="number" name="admin_port" value="8080" required>
                </div>
                <h3>管理员账户</h3>
                <div class="form-group">
                    <label>管理员用户名</label>
                    <input type="text" name="admin_user" value="admin" required>
                </div>
                <div class="form-group">
                    <label>管理员密码 (至少 6 位)</label>
                    <input type="password" name="admin_pass" required minlength="6">
                </div>
                <div class="form-group">
                    <label>管理员邮箱</label>
                    <input type="email" name="admin_email" value="admin@localhost.com" required>
                </div>
                <h3>邮件服务</h3>
                <div class="form-group">
                    <label>邮件服务器主机名 (用于 SMTP EHLO / MX 记录)</label>
                    <input type="text" name="mail_hostname" value="<?= 'mail.' . ($_SERVER['SERVER_NAME'] ?? 'localhost') ?>" required>
                </div>
                <div class="form-group">
                    <label>应用 URL</label>
                    <input type="text" name="app_url" value="<?= 'http://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') ?>" required>
                </div>
                <div class="form-group">
                    <label>时区</label>
                    <input type="text" name="timezone" value="Asia/Shanghai" required>
                </div>
                <p>
                    <button type="submit" class="btn">开始安装</button>
                </p>
            </form>
        <?php elseif ($step === 3): ?>
            <h2>🎉 安装完成</h2>
            <div class="success-box">
                <p><strong>系统已成功安装！</strong></p>
                <p>请妥善保管你的管理员账户信息。</p>
            </div>
            <h3 style="margin-top:24px;">后续操作</h3>
            <ol>
                <li>访问 <a href="/<?= htmlspecialchars(mail_sys_env_read('ADMIN_PATH', 'admin')) ?>/" target="_blank">后台管理</a>，登录管理界面</li>
                <li>在「域名管理」中添加你的域名</li>
                <li>在「邮箱管理」中创建用户邮箱</li>
                <li>在「端口管理」中确认 SMTP/POP3/IMAP 端口（可自定义）</li>
                <li>执行 <code>bash scripts/install-services.sh</code> 启动邮件协议服务</li>
                <li>在域名 DNS 中配置 MX/A/TXT 记录（后台可查询）</li>
            </ol>
            <p style="margin-top:20px;">
                <a class="btn" href="/<?= htmlspecialchars(mail_sys_env_read('ADMIN_PATH', 'admin')) ?>/">进入后台</a>
                <a class="btn btn-secondary" href="/">访问前台</a>
            </p>
        <?php endif; ?>
    </div>
</div>
</body>
</html>
